<?php
	require_once 'include/language/en_us.lang.php';
	
	function vtws_describeobject($elementType,$user){
		
		global $app_strings,$current_user;
		
		$current_user = $user;
		$crmObject = new VtigerCRMObject($elementType);
		
		$types = vtws_listtypes($user);
		if(!in_array($elementType,$types['types'])){
			return new WebServiceError(WebServiceErrorCode::$ACCESSDENIED,"Permission to perform the operation is denied");
		}
		
		$meta = new VtigerCRMObjectMeta($crmObject,$user);
		if(!$meta->hasAccess()){
			return new WebServiceError(WebServiceErrorCode::$ACCESSDENIED,"Permission to access object type is denied");
		}
		
		$label = (isset($app_strings[$elementType]))? $app_strings[$elementType]:$elementType;
		$createable = (strcasecmp(isPermitted($elementType,"Save"),'yes')===0)? true:false;
		$updateable = (strcasecmp(isPermitted($elementType,"EditView"),'yes')===0)? true:false;
		$deleteable = $meta->hasDeleteAccess();
		$retrieveable = $meta->hasReadAccess();
		$fields = vtws_getModuleFields($meta,$user);
		$userGroupIds = vtws_getUserWebservicesGroups($crmObject,$user);
		return array("label"=>$label,"name"=>$elementType,"createable"=>$createable,"updateable"=>$updateable,
				"deleteable"=>$deleteable,"retrieveable"=>$retrieveable,"fields"=>$fields,'groups'=>$userGroupIds);
	}
	
	function vtws_getModuleFields($meta,$user){
		
		$fields = array();
		$userColumns = $meta->getUserAccessibleColumns();
		foreach($userColumns as $index=>$column){
			array_push($fields ,vtws_getField($column,$meta,$user));
		}
		return $fields;
	}
	
	function vtws_getField($column,$meta,$user){
		
		if(strcmp($column,$meta->getObectIndexColumn())===0){
			return vtws_getIdField($column);
		}
		
		$fieldColumnMapping = $meta->getColumnFieldMapping();
		$fieldName = $fieldColumnMapping[$column];
		require 'modules/'.$meta->getObjectName().'/language/en_us.lang.php';
		$fieldLabel = vtws_getFieldLabelKey($column,$meta->getObjectId());
		if(isset($mod_strings[$fieldLabel])){
			$fieldLabel = $mod_strings[$fieldLabel];
		}
		$isMandatory = in_array($fieldName,$meta->getMandatoryFields());
		$detail = vtws_getFieldDetail($column,$meta,$user);
		return array('name'=>$fieldName,'label'=>$fieldLabel,'mandatory'=>$isMandatory,'type'=>$detail['type'],
						'default'=>$detail['default'],'nullable'=>$detail['nullable'],"editable"=>$detail['editable']);		
	}
	
	function vtws_getFieldDetail($column,$meta,$user){
		$uitype = vtws_getFieldUIType($column,$meta->getObjectId());
		$type = vtws_getFieldTypeForUIType($uitype);
		if($type == null){
			$typeMapping = $meta->getColumnDataTypeMapping();
			$type = vtws_getFieldTypeFromTypeOfData($typeMapping[$column]);
		}
		
		$tables = $meta->getColumnTableMapping();
		$table = $tables[$column];
		$details = vtws_getFieldDetailFromTable($column,$table);
		if($details["type"] !='datetime'){
			$details['type'] = $type;
		}
		$details['editable'] = vtws_isEditable($details['type'],$uitype);
		$typeDetails = vtws_getTypeDetails($column,$uitype,$details,$meta,$user);
		$typeDetails['name'] = $details['type'];
		$details['type'] = $typeDetails;
		return $details;
	}
	
	function vtws_isEditable($type,$uitype){
		if(strcasecmp($type,"autogenerated")===0 || strcasecmp($type,"ID")===0){
			return false;
		}
		if($uitype ==  70){
			return false;
		}
		return true;
	}
	
	function vtws_getTypeDetails($column,$uitype,$details,$meta,$user){
		$typeDetails = array();
		switch($details['type']){
			case 'reference': $typeDetails['refersTo'] = vtws_getReferenceType($uitype);
								break;
			case 'picklist': $typeDetails["picklistValues"] = vtws_getPicklistDetails($column,$uitype,$meta,$user);
								$typeDetails['defaultValue'] = $typeDetails["picklistValues"][0]['value'];
								break;
			case 'date': $typeDetails['format'] = $user->date_format;
		}
		return $typeDetails;
	}
	
	function vtws_getPicklistDetails($column,$uitype,$meta,$user){
		$hardCodedPickListNames = array("hdntaxtype");
		$hardCodedPickListValues = array("hdntaxtype"=>array(array("label"=>"Individual","value"=>"individual"),
														array("label"=>"Group","value"=>"group")));
		$fieldColumnMapping = $meta->getColumnFieldMapping();
		$fieldName = $fieldColumnMapping[$column];
		$fieldName = strtolower($fieldName);
		if(in_array($fieldName,$hardCodedPickListNames)){
			return $hardCodedPickListValues[$fieldName];
		}
		
		return vtws_getPickListOptions($fieldName,$user);
		
	}
	
	function vtws_getPickListOptions($fieldName,$user){
		
		global $adb;
		
		$options = array();
		$sql = "select * from vtiger_picklist where name=?";
		$result = $adb->pquery($sql,array($fieldName));
		$numRows = $adb->num_rows($result);
		if($numRows == 0){
			$sql = "select * from vtiger_$fieldName";
			$result = $adb->pquery($sql,array());
			$numRows = $adb->num_rows($result);
			for($i=0;$i<$numRows;++$i){
				$elem = array();
				$elem["label"] = $adb->query_result($result,$i,$fieldName);
				$elem["value"] = $adb->query_result($result,$i,$fieldName);
				array_push($options,$elem);
			}
		}else{
			$details = vt_getPickListValues($fieldName,$user->roleid);
			for($i=0;$i<sizeof($details);++$i){
				$elem = array();
				$elem["label"] = $details[$i];
				$elem["value"] = $details[$i];
				array_push($options,$elem);
			}
		}
		return $options;
	}
	
	function vtws_getReferenceType($uitype){
		
		global $adb;
		$sql = "select * from vtiger_ws_fieldtype where uitype=?";
		$result = $adb->pquery($sql,array($uitype));
		$fieldTypeId = null;
		if($result != null && isset($result)){
			if($adb->num_rows($result)>0){
				$fieldTypeId = $adb->query_result($result,0,"fieldtypeid");
			}
		}
		
		$referenceTypes = array();
		$sql = "select * from vtiger_ws_referencetype where fieldtypeid=?";
		$result = $adb->pquery($sql,array($fieldTypeId));
		$numRows = $adb->num_rows($result);
		for($i=0;$i<$numRows;++$i){
			array_push($referenceTypes,$adb->query_result($result,$i,"type"));
		}
		return $referenceTypes;
	}
	
	function vtws_getFieldTypeFromTypeOfData($typeofdata){
		switch($typeofdata){
			case 'T': return "time";
			case 'D':
			case 'DT': return "date";
			case 'E': return "email";
			case 'N':
			case 'NN': return "double";
			case 'P': return "password";
			case 'I': return "integer";
			case 'V':
			default: return "string";
		}
	}
	
	function vtws_getFieldDetailFromTable($column,$table){
		
		global $adb;
		$sql = "desc $table";
		$result = $adb->pquery($sql,array());
		$details = array();
		$details['type'] = null;
		$details['default'] = "";
		$details['nullable'] = true;
		if($result != null && isset($result)){
			$numRows = $adb->num_rows($result);
			for($i=0;$i<$numRows;++$i){
				$name = $adb->query_result($result,$i,"field");
				if($name == $column){
					$details['type'] = $adb->query_result($result,$i,"type");
					$default = $adb->query_result($result,$i,"default");
					$details['nullable'] = ($adb->query_result($result,$i,"null")=="NO")? false: true;
					$details['default'] = ($default!="" && isset($default))? $default: "";
					break;
				}
			}
		}
		return $details;
	}
	
	function vtws_getFieldTypeForUIType($uitype){
		global $adb;
		$sql = "select * from vtiger_ws_fieldtype where uitype=?";
		$result = $adb->pquery($sql,array($uitype));
		if($result != null && isset($result)){
			if($adb->num_rows($result)>0){
				return $adb->query_result($result,0,"fieldtype");
			}
		}
		return null;
	}
	
	function vtws_getFieldUIType($column,$tabId){
		global $adb;
		$sql = "select * from vtiger_field where columnname=? and tabid=?";
		$result = $adb->pquery($sql,array($column,$tabId));
		if($result != null && isset($result)){
			if($adb->num_rows($result)>0){
				return $adb->query_result($result,0,"uitype");
			}
		}
		return null;
	}
	
	function vtws_getIdField($column){
		return array('name'=>'id','label'=>$column,'mandatory'=>false,'type'=>'ID','editable'=>false,'type'=>
						array('name'=>'autogenerated'),'nullable'=>false,'default'=>"");
	}
	
	function vtws_getFieldLabelKey($column,$tabId){
		
		global $adb;
		$sql = "select * from vtiger_field where columnname=? and tabid=?";
		$result = $adb->pquery($sql,array($column,$tabId));
		if($result != null && isset($result)){
			if($adb->num_rows($result)>0){
				return $adb->query_result($result,0,"fieldlabel");
			}
		}
		return null;
	}
	
?>